# Generate csv files 


In [1]:
#from IPython.core.display import HTML
#HTML("<script>Jupyter.notebook.kernel.restart()</script>")
%load_ext autoreload
%autoreload 2

from preprocessing import *

### Set the parameters below carefully

In [2]:
%%time
###  YOU MAY NEED TO CHANGE THE GRID FOLDER!!!
#### Closed grids - first neighbours
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_periodic_6561_50"
#grid_folder = "/home/rio/data/phase_transitions/second_neighbours_periodic_6561_50"
#### Open grids - first neighbours
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_50"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_70"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_90"
grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_110"
list_of_hamiltonians, raw_data = load_hamiltonians(grid_folder)
print("shape of raw_data: ", raw_data.shape)
print("len list_of_hamiltonians: ", len(list_of_hamiltonians))

loading hamiltonians: 100%|██████████| 6561/6561 [02:14<00:00, 48.94it/s]


shape of raw_data:  (1443420, 224)
len list_of_hamiltonians:  6561
CPU times: user 1min 15s, sys: 16.4 s, total: 1min 31s
Wall time: 2min 43s


In [3]:
%%time
###  YOU MAY NEED TO CHANGE THE ALLOWED WINDINGS!!!
#allowed_windings = [-1, 0, 1, 2]
allowed_windings = [0, 1]
###  YOU MAY NEED TO CHANGE THE VALUE OF EPSILON!!!
epsilon = 0.003
###  YOU MAY NEED TO CHOOSE ANOTHER FILENAME!!!
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_periodic_6561_50.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/second_neighbours_periodic_6561_50.csv"
######### Periodic grids - First neighbours  
######### Open grids - Fist neighbours 
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_50.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_70.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_90.csv"
csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_110.csv"
to_csv = True
dataframe = make_dataframe(raw_data, list_of_hamiltonians, allowed_windings = allowed_windings, epsilon = epsilon, \
                           csv_name = csv_name, to_csv = to_csv)

CPU times: user 4min 20s, sys: 14.7 s, total: 4min 35s
Wall time: 4min 39s


In [4]:
dataframe.info()
dataframe.head()
#dataframe.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1443420 entries, 0 to 1443419
Columns: 228 entries, id to feat219
dtypes: float64(3), int32(1), int64(2), object(222)
memory usage: 2.4+ GB


id                  path   t1   t2   winding  phase  pred_phase type_of  \
0   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666    test   
1   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666    test   
2   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666    test   
3   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666    test   
4   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666    test   

       feat0      feat1  ...    feat210    feat211    feat212    feat213  \
0  -0.002704   0.001352  ...  -0.012138   0.013478  -0.009451   0.010795   
1  -0.005406   0.002704  ...   0.024077  -0.026683   0.018808  -0.021451   
2  -0.008104   0.004056  ...  -0.035623   0.039351  -0.027979   0.031829   
3   0.010795  -0.005406  ...  -0.046586   0.051224  -0.036873   0.041797   
4  -0.013478   0.006756  ...  -0.056788   0.062064  -0.045402   0.051224   

     feat214    feat215    feat216    feat217    feat218    feat219  
0  -0.006756   0.008104  -0.004056   0.005406  -0.001352   0.002704  
1   0.013478  -0.016149   0.008104  -0.010795   0.002704  -0.005406  
2  -0.020131   0.024077  -0.012138   0.016149  -0.004056   0.008104  
3  -0.026683   0.031829  -0.016149   0.021451  -0.005406   0.010795  
4  -0.033101   0.039351  -0.020131   0.026683  -0.006756   0.013478  

[5 rows x 228 columns]

#### Checking t values are row-major sorted

In [5]:
#np.set_printoptions(threshold=np.inf)
t_array = dataframe[["t1", "t2"]].values
print("t_array:\n", t_array)
np.set_printoptions()

t_array:
 [[-2. -2.]
 [-2. -2.]
 [-2. -2.]
 ...
 [ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]]


#### Making a grid

In [6]:
xx = dataframe.t2.values
yy = dataframe.t1.values
print("xx: \n", xx)
print("yy: \n", yy)

xx: 
 [-2. -2. -2. ...  2.  2.  2.]
yy: 
 [-2. -2. -2. ...  2.  2.  2.]


#### Train/test 

In [7]:
n_total = len(dataframe)
n_train = len(dataframe[dataframe.type_of == "train"])
n_test = len(dataframe[dataframe.type_of == "test"])
print("% train: ", n_train/n_total)
print("% test: ", n_test/n_total)
print("% train + test: ", (n_train+n_test)/n_total)

% train:  0.8306660570035056
% test:  0.16933394299649443
% train + test:  1.0


In [15]:
# A view of train data
dataframe[dataframe.type_of == "train"].head(1000)

id                         path   t1    t2   winding  phase  pred_phase  \
4620  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4621  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4622  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4623  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4624  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4625  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4626  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4627  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4628  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4629  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4630  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4631  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4632  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4633  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4634  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4635  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4636  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4637  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4638  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4639  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4640  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4641  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4642  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4643  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4644  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4645  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4646  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4647  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4648  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
4649  21  H_-2_-0.95_-0.000981303.dat -2.0 -0.95 -0.000981      0         666   
...   ..                          ...  ...   ...       ...    ...         ...   
5590  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5591  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5592  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5593  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5594  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5595  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5596  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5597  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5598  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5599  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5600  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5601  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5602  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5603  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5604  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5605  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5606  25  H_-2_-0.75_-0.000650758.dat -2.0 -0.75 -0.000651      0         666   
5607  25  H_-2_-0.75_-0.000650758.dat

In [16]:
# A view of test data
dataframe[dataframe.type_of == "test"].head(1000)

id                       path   t1   t2   winding  phase  pred_phase  \
0     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
1     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
2     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
3     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
4     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
5     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
6     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
7     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
8     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
9     0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
10    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
11    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
12    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
13    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
14    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
15    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
16    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
17    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
18    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
19    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
20    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
21    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
22    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
23    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
24    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
25    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
26    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
27    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
28    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
29    0       H_-2_-2_0.501338.dat -2.0 -2.0  0.501338      0         666   
..   ..                        ...  ...  ...       ...    ...         ...   
970   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
971   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
972   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
973   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
974   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
975   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
976   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
977   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
978   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
979   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
980   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
981   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
982   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
983   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
984   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
985   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
986   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
987   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
988   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
989   4  H_-2_-1.8_-0.00976312.dat -2.0 -1.8 -0.009763      0         666   
9

#### Unique winding values

In [17]:
np.unique(dataframe.phase.values)

array([0, 1], dtype=int32)

#### Visualizing grid

In [49]:
fig_params={"figsize": (8,6)} 
val_params={"marker": "s", "s": 64, "alpha": 0.2, "color": "salmon", "label": "val"}
test_params={"marker": "s", "s": 64, "alpha": 0.2, "color": "blue", "label": "test"}
train_params={"marker": "o", "s": 8, "color": "red", "label": "train"}
legend_params={"framealpha": 1}
xlabel_params={"xlabel": "$t_1$", "fontsize": 18}
ylabel_params={"ylabel": "$t_2$", "fontsize": 18}
title_params={}
savefig_params = None
simulation.visualize_scatter_2d(fig_params = fig_params, val_params = val_params, test_params = test_params,\
                                train_params = train_params, legend_params = legend_params, \
                                xlabel_params = xlabel_params, ylabel_params = ylabel_params, title_params = title_params,\
                               savefig_params = savefig_params)

NameError: name 'simulation' is not defined