# Generate csv files 


In [1]:
#from IPython.core.display import HTML
#HTML("<script>Jupyter.notebook.kernel.restart()</script>")
%load_ext autoreload
%autoreload 2

from preprocessing import *

### Set the parameters below carefully

In [12]:
%%time
###  YOU MAY NEED TO CHANGE THE GRID FOLDER!!!
########## First neighbour grids
#### Periodic grids - first neighbours
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_periodic_6561_50"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_periodic_6561_70"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_periodic_6561_90"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_periodic_6561_110"
#### Open grids - first neighbours
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_50"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_70"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_90"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_110"

########## Second neighbour grids
#### Periodic grids - second neighbours
grid_folder = "/home/rio/data/phase_transitions/second_neighbours_periodic_6561_50"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_periodic_6561_70"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_periodic_6561_90"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_periodic_6561_110"
#### Open grids - second neighbours
#grid_folder = "/home/rio/data/phase_transitions/second_neighbours_open_6561_50"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_70"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_90"
#grid_folder = "/home/rio/data/phase_transitions/first_neighbours_open_6561_110"

list_of_hamiltonians, raw_data = load_hamiltonians(grid_folder)
print("shape of raw_data: ", raw_data.shape)
print("len list_of_hamiltonians: ", len(list_of_hamiltonians))

loading hamiltonians: 100%|██████████| 6561/6561 [01:10<00:00, 93.30it/s] 


shape of raw_data:  (656100, 104)
len list_of_hamiltonians:  6561
CPU times: user 23.6 s, sys: 4.94 s, total: 28.5 s
Wall time: 1min 16s


In [14]:
%%time
###  YOU MAY NEED TO CHANGE THE ALLOWED WINDINGS!!!
allowed_windings = [-1, 0, 1, 2]
#allowed_windings = [0, 1]
###  YOU MAY NEED TO CHANGE THE VALUE OF EPSILON!!!
epsilon = 0.01
###  YOU MAY NEED TO CHOOSE ANOTHER FILENAME!!!
#csv_name = "/home/rio/data/phase_transitions/csv/second_neighbours_periodic_6561_50.csv"
########## First neighbour grids
##### Periodic grids - First neighbours 
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_periodic_6561_50.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_periodic_6561_70.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_periodic_6561_90.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_periodic_6561_110.csv"
##### Open grids - Fist neighbours 
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_50.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_70.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_90.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_110.csv"

########## Second neighbour grids
##### Periodic grids - Second neighbours 
csv_name = "/home/rio/data/phase_transitions/csv/second_neighbours_periodic_6561_50.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_periodic_6561_70.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_periodic_6561_90.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_periodic_6561_110.csv"
##### Open grids - Second neighbours 
#csv_name = "/home/rio/data/phase_transitions/csv/second_neighbours_open_6561_50.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_70.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_90.csv"
#csv_name = "/home/rio/data/phase_transitions/csv/first_neighbours_open_6561_110.csv"

to_csv = True
dataframe = make_dataframe(raw_data, list_of_hamiltonians, allowed_windings = allowed_windings, epsilon = epsilon, \
                           csv_name = csv_name, to_csv = to_csv)

CPU times: user 55.5 s, sys: 3.06 s, total: 58.5 s
Wall time: 54.9 s


In [15]:
dataframe.info()
dataframe.head()
#dataframe.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 656100 entries, 0 to 656099
Columns: 108 entries, id to feat99
dtypes: float64(3), int32(1), int64(2), object(102)
memory usage: 538.1+ MB


id                  path   t1   t2   winding  phase  pred_phase type_of  \
0   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338    999         666    test   
1   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338    999         666    test   
2   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338    999         666    test   
3   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338    999         666    test   
4   0  H_-2_-2_0.501338.dat -2.0 -2.0  0.501338    999         666    test   

       feat0      feat1  ...     feat90     feat91     feat92     feat93  \
0  -0.130965   0.301130  ...  -0.080279  -0.115687  -0.174988   0.245064   
1  -0.130965  -0.301130  ...  -0.080279   0.115687  -0.174988  -0.245064   
2  -0.148414  -0.042467  ...   0.185442  -0.080620  -0.066211  -0.121339   
3  -0.069630  -0.026147  ...   0.102009  -0.100671  -0.081002  -0.020715   
4   0.010206  -0.014625  ...   0.047555  -0.041368  -0.018852  -0.017673   

      feat94     feat95     feat96     feat97     feat98     feat99  
0   0.319763  -0.059082  -0.000556  -0.245133  -0.301130   0.130965  
1   0.319763   0.059082  -0.000556   0.245133  -0.301130  -0.130965  
2  -0.151700   0.192513   0.191642  -0.050956  -0.042467  -0.148414  
3  -0.058717   0.115834   0.118274  -0.054666  -0.026147  -0.069630  
4  -0.023377   0.031447   0.010280   0.000925   0.014625  -0.010206  

[5 rows x 108 columns]

#### Checking t values are row-major sorted

In [16]:
#np.set_printoptions(threshold=np.inf)
t_array = dataframe[["t1", "t2"]].values
print("t_array:\n", t_array)
np.set_printoptions()

t_array:
 [[-2. -2.]
 [-2. -2.]
 [-2. -2.]
 ...
 [ 2.  2.]
 [ 2.  2.]
 [ 2.  2.]]


#### Making a grid

In [17]:
xx = dataframe.t2.values
yy = dataframe.t1.values
print("xx: \n", xx)
print("yy: \n", yy)

xx: 
 [-2. -2. -2. ...  2.  2.  2.]
yy: 
 [-2. -2. -2. ...  2.  2.  2.]


#### Train/test 

In [18]:
n_total = len(dataframe)
n_train = len(dataframe[dataframe.type_of == "train"])
n_test = len(dataframe[dataframe.type_of == "test"])
print("% train: ", n_train/n_total)
print("% test: ", n_test/n_total)
print("% train + test: ", (n_train+n_test)/n_total)

% train:  0.8414875781130925
% test:  0.15851242188690748
% train + test:  1.0


In [8]:
# A view of train data
dataframe[dataframe.type_of == "train"].head(1000)

id                     path   t1    t2   winding  phase  pred_phase  \
1300  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1301  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1302  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1303  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1304  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1305  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1306  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1307  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1308  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1309  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1310  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1311  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1312  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1313  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1314  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1315  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1316  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1317  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1318  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1319  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1320  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1321  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1322  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1323  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1324  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1325  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1326  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1327  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1328  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
1329  13  H_-2_-1.35_-1.00951.dat -2.0 -1.35 -1.009513     -1         666   
...   ..                      ...  ...   ...       ...    ...         ...   
2270  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2271  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2272  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2273  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2274  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2275  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2276  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2277  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2278  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2279  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2280  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2281  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2282  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2283  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2284  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2285  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2286  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2287  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2288  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
2289  22   H_-2_-0.9_-1.00473.dat -2.0 -0.90 -1.004733     -1         666   
22

In [9]:
# A view of test data
dataframe[dataframe.type_of == "test"].head(1000)

id                     path   t1    t2   winding  phase  pred_phase  \
0     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
1     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
2     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
3     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
4     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
5     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
6     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
7     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
8     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
9     0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
10    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
11    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
12    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
13    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
14    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
15    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
16    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
17    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
18    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
19    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
20    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
21    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
22    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
23    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
24    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
25    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
26    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
27    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
28    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
29    0     H_-2_-2_0.501338.dat -2.0 -2.00  0.501338    999         666   
..   ..                      ...  ...   ...       ...    ...         ...   
970   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
971   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
972   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
973   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
974   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
975   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
976   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
977   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
978   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
979   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
980   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
981   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
982   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
983   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
984   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
985   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
986   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
987   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
988   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
989   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708     -1         666   
990   9  H_-2_-1.55_-1.01471.dat -2.0 -1.55 -1.014708

#### Unique winding values

In [10]:
np.unique(dataframe.phase.values)

array([ -1,   0,   1,   2, 999], dtype=int32)

#### Visualizing grid

In [49]:
fig_params={"figsize": (8,6)} 
val_params={"marker": "s", "s": 64, "alpha": 0.2, "color": "salmon", "label": "val"}
test_params={"marker": "s", "s": 64, "alpha": 0.2, "color": "blue", "label": "test"}
train_params={"marker": "o", "s": 8, "color": "red", "label": "train"}
legend_params={"framealpha": 1}
xlabel_params={"xlabel": "$t_1$", "fontsize": 18}
ylabel_params={"ylabel": "$t_2$", "fontsize": 18}
title_params={}
savefig_params = None
simulation.visualize_scatter_2d(fig_params = fig_params, val_params = val_params, test_params = test_params,\
                                train_params = train_params, legend_params = legend_params, \
                                xlabel_params = xlabel_params, ylabel_params = ylabel_params, title_params = title_params,\
                               savefig_params = savefig_params)

NameError: name 'simulation' is not defined