# Simulation template 

In this notebook we run the machine learning analysis of topological phase transitions occurring  in both nearest-neighbours SSH models (ssh1) and second neighbours models (ssh2) as decribed in the paper [Machine learning topological phases in real space](https://arxiv.org/abs/1901.01963). Here the simulation is run with features generated from fourier components in the first scenario. This scenario is characterized by using only the EVEN wavevector space eigenmodes, computed from ALL real space components.

## Defining parameters

In [1]:
%%time
%load_ext autoreload
%autoreload 2
from simulation import *

CPU times: user 754 ms, sys: 267 ms, total: 1.02 s
Wall time: 584 ms


In [2]:
%%time
### Dataset and simulation parameters
#csv_path = SSH2_PERIODIC_100_6561_CSV 
csv_path = SSH1_PERIODIC_100_6561_CSV 
model_name = "DecisionTreeClassifier"
model_kw = {"criterion":"entropy"}
allowed_windings = [0,1]
#allowed_windings = [-1,0,1,2]
simulation_dir = SSH1_REAL_SPACE_ALL_SITES
#simulation_dir = SSH2_PERIODIC_ENGINEERED_100_6561_SIMULATION_DIR
val_split = 0.9  
features_to_use = None
shuffle_features = False
random_state = 763

### Fourier features
fourier_mode = "dst"
fourier_features_to_use = None
fourier_real = "imag"
fourier_normalize = False
fourier_fillna = False

### Running a simulation
n_experiments = 5
start_n = 0
fit_params = None
#mode=mode
shuffle_rows = True
pred_params = None
random_features = False
######### DON'T SET THIS TO TRUE UNLESS YOUR DATASET IS SMALL!! WILL FLOOD YOUR MEMORY!!!
store_in_lists = False   
########## BELOW ARE THE PARAMETERS THAT CONTROL WHAT WILL BE SAVED
save_eigenvector=True
save_hamiltonian=True 
save_accuracy=True 
save_models=True

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 4.53 µs


In [3]:
# Parameters
model_kw = {"criterion": "entropy"}
allowed_windings = [0, 1]
val_split = 0.9
features_to_use = None
shuffle_features = False
n_experiments = 100
start_n = 0
fit_params = None
shuffle_rows = True
pred_params = None
random_features = False
store_in_lists = False
save_eigenvector = True
save_hamiltonian = True
save_accuracy = True
save_models = True
csv_path = "/home/rio/ssh_csvs/ssh1/periodic_100_6561.csv"
model_name = "DecisionTreeClassifier"
simulation_dir = (
    "/home/rio/ssh_simulations/ssh1/periodic_100_6561/dst_best_04_wavevector_sites"
)
random_state = 1019
fourier_features_to_use = [0, 18, 28, 30]
fourier_mode = "dst"
fourier_real = None
fourier_normalize = False
fourier_fillna = False


In [4]:
%%time
#Starting an instance of Simulation with a decision tree
model = DecisionTreeClassifier(criterion="entropy")
#dict_args = {"csv_path":csv_path, "model":model, "allowed_windings":allowed_windings,\
#             "simulation_dir":simulation_dir, "val_split":val_split, "features_to_use":features_to_use,\
#            "shuffle_features":shuffle_features, "random_state":random_state}
simulation = Simulation(csv_path,model_name,model_kw,allowed_windings,simulation_dir,val_split,features_to_use,\
                       shuffle_features,fourier_mode,fourier_features_to_use,fourier_real,\
                       fourier_normalize, fourier_fillna , random_state)
#simulation = Simulation(**dict_args)


#(self, csv_path, model_name, model_kw, allowed_windings, simulation_dir = None, val_split = 0, 
# features_to_use = None, shuffle_features = False, fourier_mode=None, fourier_features_to_use=None,
# fourier_real = False, fourier_normalize = False, Fourier_fillna=False, random_state = None):



print("Info on all data: \n")
simulation.dataframe.info()
simulation.dataframe.head()

Info on all data: 

<class 'pandas.core.frame.DataFrame'>
Int64Index: 656100 entries, 0 to 656099
Columns: 108 entries, id to feat99
dtypes: float64(103), int32(3), object(2)
memory usage: 538.1+ MB
CPU times: user 5.91 s, sys: 600 ms, total: 6.51 s
Wall time: 5.9 s


id                  path   t1   t2   winding  phase  pred_phase type_of  \
0   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
1   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
2   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
3   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
4   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   

      feat0     feat1  ...    feat90    feat91    feat92    feat93    feat94  \
0  0.100000  0.100000  ...  0.100000  0.100000  0.100000  0.100000  0.100000   
1  0.141421  0.141142  ...  0.114412  0.108967  0.123928  0.119406  0.131490   
2  0.141421  0.140306  ...  0.043702  0.026500  0.075777  0.060214  0.103092   
3 -0.100000  0.100000  ... -0.100000  0.100000 -0.100000  0.100000 -0.100000   
4  0.000509 -0.008372  ... -0.082713 -0.089753 -0.067684 -0.075347 -0.051587   

     feat95    feat96    feat97    feat98    feat99  
0  0.100000  0.100000  0.100000  0.100000  0.100000  
1  0.127962  0.136978  0.134500  0.140306  0.138916  
2  0.090145  0.123928  0.114412  0.136978  0.131490  
3  0.100000 -0.100000  0.100000 -0.100000  0.100000  
4 -0.059753 -0.034677 -0.043217 -0.017220 -0.026000  

[5 rows x 108 columns]

####  Fourier features

In [5]:
%%time
#simulation.generate_fourier_df()
if simulation.fourier_mode is not None:
    simulation.fourier_dataframe.info() 
    simulation.fourier_dataframe.sample(15)


<class 'pandas.core.frame.DataFrame'>
Int64Index: 656100 entries, 0 to 656099
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   id          656100 non-null  int32  
 1   path        656100 non-null  object 
 2   t1          656100 non-null  float64
 3   t2          656100 non-null  float64
 4   winding     656100 non-null  float64
 5   phase       656100 non-null  int32  
 6   pred_phase  656100 non-null  int32  
 7   type_of     656100 non-null  object 
 8   dst_feat0   656100 non-null  float64
 9   dst_feat18  656100 non-null  float64
 10  dst_feat28  656100 non-null  float64
 11  dst_feat30  656100 non-null  float64
dtypes: float64(7), int32(3), object(2)
memory usage: 57.6+ MB
CPU times: user 75.7 ms, sys: 0 ns, total: 75.7 ms
Wall time: 75 ms


In [6]:
print("features_to_use: ")
print("\n")
print(simulation.features_to_use)
if simulation.features_to_use is not None:
    print("Number of real space features:")
    print("\n")
    print(len(simulation.features_to_use))
print("\n")
print("fourier_features: ")
print("\n")
print(simulation.fourier_features)
print("\n")
if simulation.fourier_features is not None:
    print("Number of Fourier features: ")
    print("\n")
    print(len(simulation.fourier_features))
print("\n")
print("Fourier operator: ")
print(simulation.fourier_operator)
print("\n")
if simulation.fourier_operator is not None:
    print("Shape of Fourier operator: ")
    print(simulation.fourier_operator.shape)

features_to_use: 


None


fourier_features: 


['dst_feat0', 'dst_feat18', 'dst_feat28', 'dst_feat30']


Number of Fourier features: 


4


Fourier operator: 
[[ 0.12558104  1.85955297  1.93716632  1.85955297]
 [ 0.25066647  1.36909421 -0.96350735 -1.36909421]
 [ 0.37476263 -0.85155858 -1.45793725 -0.85155858]
 [ 0.49737977 -1.99605346  1.68865585  1.99605346]
 [ 0.61803399 -0.61803399  0.61803399 -0.61803399]
 [ 0.73624911  1.54102649 -1.99605346 -1.54102649]
 [ 0.85155858  1.75261336  0.37476263  1.75261336]
 [ 0.96350735 -0.25066647  1.8096541   0.25066647]
 [ 1.07165359 -1.93716632 -1.27484798 -1.93716632]
 [ 1.1755705  -1.1755705  -1.1755705   1.1755705 ]
 [ 1.27484798  1.07165359  1.85955297  1.07165359]
 [ 1.36909421  1.9645745   0.25066647 -1.9645745 ]
 [ 1.45793725  0.37476263 -1.9842294   0.37476263]
 [ 1.54102649 -1.68865585  0.73624911  1.68865585]
 [ 1.61803399 -1.61803399  1.61803399 -1.61803399]
 [ 1.68865585  0.49737977 -1.54102649 -0.49737977]
 [ 1.75261336  1.9842294

In [7]:
#a = np.array([1+1j,2+3j,4+8j])
#np.imag(a)

In [8]:
#plt.plot(np.imag(simulation.fourier_operator[:,0]))

In [9]:
#np.sin(np.pi/(50))*2

In [10]:
#2*np.sin(np.pi/50*49)

In [11]:
#simulation.dataframe.iloc[331456,:]

In [12]:
#for ix, obj in enumerate(simulation.dataframe.iloc[331456,:].values):
#    print(ix,obj)

In [13]:
#simulation.fourier_engineered_dataframe.dct_feat0

In [14]:
#simulation.features

In [15]:
#simulation.fourier_matrix

In [16]:
#1/simulation.n_features*simulation.dataframe.loc[:,simulation.features].sum(axis=1)

In [17]:
#df_2 = simulation.fourier_engineered_dataframe[simulation.fourier_engineered_dataframe.phase==2]
#df_2.describe()

In [18]:
#df_1 = simulation.fourier_engineered_dataframe[simulation.fourier_engineered_dataframe.phase==1]
#df_1.describe()

In [19]:
#df_0 = simulation.fourier_engineered_dataframe[simulation.fourier_engineered_dataframe.phase==0]
#df_0.describe()

In [20]:
#plt.figure(figsize=(10,10))
#plt.scatter(df_1.fourier_feat0,df_1.fourier_feat2)
#plt.scatter(df_0.fourier_feat0,df_0.fourier_feat2,alpha=0.4)

In [21]:
#plt.scatter(df_0.fourier_feat0,df_0.fourier_feat2,alpha=0.4)

In [22]:
#plt.scatter(df_2.fourier_feat0,df_2.fourier_feat2)

In [23]:
#df_1.hist(figsize=(15,15))

In [24]:
#df_0.hist(figsize=(15,15))

#### Checking initialization

In [25]:
%%time
n_features = simulation.n_features
n_hamiltonians = simulation.n_hamiltonians
n_ts = simulation.n_ts

print("n_features: ", n_features)
print("n_hamiltonians: ", n_hamiltonians)
print("n_ts: ", n_ts)

n_features:  100
n_hamiltonians:  6561
n_ts:  2
CPU times: user 153 µs, sys: 20 µs, total: 173 µs
Wall time: 97 µs


In [26]:
%%time
n_total = len(simulation.dataframe)
n_train = len(simulation.dataframe[simulation.dataframe.type_of == "train"])
n_val = len(simulation.dataframe[simulation.dataframe.type_of == "val"])
n_test = len(simulation.dataframe[simulation.dataframe.type_of == "test"])
n_train_hamiltonians = len(simulation.train_ids)
n_val_hamiltonians = len(simulation.val_ids)
n_test_hamiltonians = len(simulation.test_ids)
n_total_hamiltonians = n_train_hamiltonians + n_val_hamiltonians + n_test_hamiltonians

print("% train: ", n_train/n_total)
print("% val: ",  n_val/n_total)
print("% test: ", n_test/n_total)
print("% train + val + test: ", (n_train+n_val+n_test)/n_total)
print("\n")
print("number of train hamiltonians: ", n_train_hamiltonians)
print("number of val hamiltonians: ", n_val_hamiltonians)
print("number of test hamiltonians: ", n_test_hamiltonians)
print("total number of hamiltonians: ", n_total_hamiltonians)
print("\n")
print("train ids: ", simulation.train_ids)
print("val ids: ", simulation.val_ids)
print("test ids: ", simulation.test_ids)

% train:  0.846822130772748
% val:  0.0
% test:  0.15317786922725193
% train + val + test:  1.0


number of train hamiltonians:  5556
number of val hamiltonians:  0
number of test hamiltonians:  1005
total number of hamiltonians:  6561


train ids:  [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201

## Running a simulation

In [27]:

%%time
simulation.run_simulation(n_experiments, start_n, fit_params,shuffle_rows, pred_params, random_features, \
                          store_in_lists, save_eigenvector, save_hamiltonian, save_accuracy,\
                          save_models)
if simulation.fourier_mode is not None:
    simulation.fourier_dataframe.head(10)

running experiments:   0%|          | 0/100 [00:00<?, ?it/s]

Simulation mode:  dst


running experiments:   1%|          | 1/100 [00:01<02:55,  1.77s/it]

running experiments:   2%|▏         | 2/100 [00:03<02:55,  1.79s/it]

running experiments:   3%|▎         | 3/100 [00:05<02:54,  1.80s/it]

running experiments:   4%|▍         | 4/100 [00:07<02:52,  1.79s/it]

running experiments:   5%|▌         | 5/100 [00:08<02:49,  1.78s/it]

running experiments:   6%|▌         | 6/100 [00:10<02:51,  1.82s/it]

running experiments:   7%|▋         | 7/100 [00:12<02:48,  1.81s/it]

running experiments:   8%|▊         | 8/100 [00:14<02:51,  1.86s/it]

running experiments:   9%|▉         | 9/100 [00:16<02:49,  1.86s/it]

running experiments:  10%|█         | 10/100 [00:18<02:48,  1.87s/it]

running experiments:  11%|█         | 11/100 [00:20<02:48,  1.90s/it]

running experiments:  12%|█▏        | 12/100 [00:22<02:47,  1.90s/it]

running experiments:  13%|█▎        | 13/100 [00:24<02:45,  1.90s/it]

running experiments:  14%|█▍        | 14/100 [00:25<02:41,  1.87s/it]

running experiments:  15%|█▌        | 15/100 [00:27<02:40,  1.89s/it]

running experiments:  16%|█▌        | 16/100 [00:29<02:34,  1.84s/it]

running experiments:  17%|█▋        | 17/100 [00:31<02:30,  1.81s/it]

running experiments:  18%|█▊        | 18/100 [00:33<02:26,  1.79s/it]

running experiments:  19%|█▉        | 19/100 [00:34<02:26,  1.81s/it]

running experiments:  20%|██        | 20/100 [00:36<02:24,  1.80s/it]

running experiments:  21%|██        | 21/100 [00:38<02:25,  1.84s/it]

running experiments:  22%|██▏       | 22/100 [00:40<02:23,  1.84s/it]

running experiments:  23%|██▎       | 23/100 [00:42<02:20,  1.82s/it]

running experiments:  24%|██▍       | 24/100 [00:44<02:18,  1.82s/it]

running experiments:  25%|██▌       | 25/100 [00:45<02:15,  1.81s/it]

running experiments:  26%|██▌       | 26/100 [00:47<02:13,  1.81s/it]

running experiments:  27%|██▋       | 27/100 [00:49<02:11,  1.81s/it]

running experiments:  28%|██▊       | 28/100 [00:51<02:09,  1.80s/it]

running experiments:  29%|██▉       | 29/100 [00:53<02:06,  1.78s/it]

running experiments:  30%|███       | 30/100 [00:54<02:06,  1.81s/it]

running experiments:  31%|███       | 31/100 [00:56<02:04,  1.81s/it]

running experiments:  32%|███▏      | 32/100 [00:58<02:02,  1.80s/it]

running experiments:  33%|███▎      | 33/100 [01:00<02:02,  1.83s/it]

running experiments:  34%|███▍      | 34/100 [01:02<02:02,  1.85s/it]

running experiments:  35%|███▌      | 35/100 [01:04<02:00,  1.85s/it]

running experiments:  36%|███▌      | 36/100 [01:05<01:57,  1.84s/it]

running experiments:  37%|███▋      | 37/100 [01:07<01:54,  1.82s/it]

running experiments:  38%|███▊      | 38/100 [01:09<01:52,  1.82s/it]

running experiments:  39%|███▉      | 39/100 [01:11<01:49,  1.80s/it]

running experiments:  40%|████      | 40/100 [01:13<01:48,  1.81s/it]

running experiments:  41%|████      | 41/100 [01:14<01:47,  1.82s/it]

running experiments:  42%|████▏     | 42/100 [01:16<01:44,  1.81s/it]

running experiments:  43%|████▎     | 43/100 [01:18<01:43,  1.82s/it]

running experiments:  44%|████▍     | 44/100 [01:20<01:41,  1.81s/it]

running experiments:  45%|████▌     | 45/100 [01:22<01:43,  1.87s/it]

running experiments:  46%|████▌     | 46/100 [01:24<01:39,  1.84s/it]

running experiments:  47%|████▋     | 47/100 [01:26<01:37,  1.84s/it]

running experiments:  48%|████▊     | 48/100 [01:27<01:35,  1.83s/it]

running experiments:  49%|████▉     | 49/100 [01:29<01:31,  1.80s/it]

running experiments:  50%|█████     | 50/100 [01:31<01:29,  1.79s/it]

running experiments:  51%|█████     | 51/100 [01:33<01:28,  1.80s/it]

running experiments:  52%|█████▏    | 52/100 [01:34<01:26,  1.80s/it]

running experiments:  53%|█████▎    | 53/100 [01:36<01:24,  1.79s/it]

running experiments:  54%|█████▍    | 54/100 [01:38<01:24,  1.84s/it]

running experiments:  55%|█████▌    | 55/100 [01:40<01:23,  1.86s/it]

running experiments:  56%|█████▌    | 56/100 [01:42<01:21,  1.85s/it]

running experiments:  57%|█████▋    | 57/100 [01:44<01:19,  1.85s/it]

running experiments:  58%|█████▊    | 58/100 [01:46<01:16,  1.83s/it]

running experiments:  59%|█████▉    | 59/100 [01:47<01:14,  1.81s/it]

running experiments:  60%|██████    | 60/100 [01:49<01:12,  1.80s/it]

running experiments:  61%|██████    | 61/100 [01:51<01:11,  1.83s/it]

running experiments:  62%|██████▏   | 62/100 [01:53<01:09,  1.82s/it]

running experiments:  63%|██████▎   | 63/100 [01:55<01:06,  1.81s/it]

running experiments:  64%|██████▍   | 64/100 [01:56<01:05,  1.83s/it]

running experiments:  65%|██████▌   | 65/100 [01:58<01:04,  1.83s/it]

running experiments:  66%|██████▌   | 66/100 [02:00<01:02,  1.83s/it]

running experiments:  67%|██████▋   | 67/100 [02:02<01:01,  1.85s/it]

running experiments:  68%|██████▊   | 68/100 [02:04<00:59,  1.87s/it]

running experiments:  69%|██████▉   | 69/100 [02:06<00:56,  1.83s/it]

running experiments:  70%|███████   | 70/100 [02:07<00:54,  1.82s/it]

running experiments:  71%|███████   | 71/100 [02:09<00:52,  1.81s/it]

running experiments:  72%|███████▏  | 72/100 [02:11<00:50,  1.80s/it]

running experiments:  73%|███████▎  | 73/100 [02:13<00:48,  1.81s/it]

running experiments:  74%|███████▍  | 74/100 [02:15<00:46,  1.79s/it]

running experiments:  75%|███████▌  | 75/100 [02:16<00:45,  1.81s/it]

running experiments:  76%|███████▌  | 76/100 [02:18<00:43,  1.81s/it]

running experiments:  77%|███████▋  | 77/100 [02:20<00:41,  1.83s/it]

running experiments:  78%|███████▊  | 78/100 [02:22<00:40,  1.84s/it]

running experiments:  79%|███████▉  | 79/100 [02:24<00:38,  1.83s/it]

running experiments:  80%|████████  | 80/100 [02:26<00:36,  1.83s/it]

running experiments:  81%|████████  | 81/100 [02:27<00:34,  1.79s/it]

running experiments:  82%|████████▏ | 82/100 [02:29<00:32,  1.80s/it]

running experiments:  83%|████████▎ | 83/100 [02:31<00:30,  1.80s/it]

running experiments:  84%|████████▍ | 84/100 [02:33<00:28,  1.77s/it]

running experiments:  85%|████████▌ | 85/100 [02:35<00:26,  1.80s/it]

running experiments:  86%|████████▌ | 86/100 [02:36<00:24,  1.78s/it]

running experiments:  87%|████████▋ | 87/100 [02:38<00:23,  1.79s/it]

running experiments:  88%|████████▊ | 88/100 [02:40<00:21,  1.76s/it]

running experiments:  89%|████████▉ | 89/100 [02:42<00:19,  1.78s/it]

running experiments:  90%|█████████ | 90/100 [02:43<00:18,  1.81s/it]

running experiments:  91%|█████████ | 91/100 [02:45<00:16,  1.85s/it]

running experiments:  92%|█████████▏| 92/100 [02:47<00:14,  1.82s/it]

running experiments:  93%|█████████▎| 93/100 [02:49<00:12,  1.84s/it]

running experiments:  94%|█████████▍| 94/100 [02:51<00:10,  1.82s/it]

running experiments:  95%|█████████▌| 95/100 [02:53<00:08,  1.80s/it]

running experiments:  96%|█████████▌| 96/100 [02:54<00:07,  1.82s/it]

running experiments:  97%|█████████▋| 97/100 [02:56<00:05,  1.84s/it]

running experiments:  98%|█████████▊| 98/100 [02:58<00:03,  1.82s/it]

running experiments:  99%|█████████▉| 99/100 [03:00<00:01,  1.79s/it]

running experiments: 100%|██████████| 100/100 [03:02<00:00,  1.83s/it]

running experiments: 100%|██████████| 100/100 [03:02<00:00,  1.82s/it]

CPU times: user 3min 1s, sys: 676 ms, total: 3min 2s
Wall time: 3min 2s


In [28]:
simulation.dataframe.head(10)

id                  path   t1   t2   winding  phase  pred_phase type_of  \
0   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
1   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
2   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
3   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
4   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
5   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
6   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
7   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
8   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   
9   0  H_-2_-2_0.509296.dat -2.0 -2.0  0.509296    999         666    test   

      feat0     feat1  ...    feat90    feat91    feat92    feat93    feat94  \
0  0.100000  0.100000  ...  0.100000  0.100000  0.100000  0.100000  0.100000   
1  0.141421  0.141142  ...  0.114412  0.108967  0.123928  0.119406  0.131490   
2  0.141421  0.140306  ...  0.043702  0.026500  0.075777  0.060214  0.103092   
3 -0.100000  0.100000  ... -0.100000  0.100000 -0.100000  0.100000 -0.100000   
4  0.000509 -0.008372  ... -0.082713 -0.089753 -0.067684 -0.075347 -0.051587   
5  0.001204 -0.016530  ... -0.134123 -0.138686 -0.118757 -0.127445 -0.095929   
6 -0.141421 -0.138980  ...  0.043375  0.067830 -0.009222  0.017385 -0.060524   
7 -0.000826  0.025688  ...  0.134753  0.124324  0.141088  0.140407  0.127608   
8  0.141417  0.136684  ... -0.115093 -0.131915 -0.061266 -0.091040  0.007717   
9  0.001302  0.036430  ...  0.082068  0.050848  0.127402  0.108132  0.141218   

     feat95    feat96    feat97    feat98    feat99  
0  0.100000  0.100000  0.100000  0.100000  0.100000  
1  0.127962  0.136978  0.134500  0.140306  0.138916  
2  0.090145  0.123928  0.114412  0.136978  0.131490  
3  0.100000 -0.100000  0.100000 -0.100000  0.100000  
4 -0.059753 -0.034677 -0.043217 -0.017220 -0.026000  
5 -0.108196 -0.067073 -0.082149 -0.034003 -0.050940  
6 -0.035502 -0.103326 -0.083403 -0.131616 -0.119589  
7  0.136771  0.096206  0.113925  0.051292  0.075079  
8 -0.027643  0.074791  0.042592  0.123363  0.102291  
9  0.138667  0.120099  0.134896  0.069268  0.097755  

[10 rows x 108 columns]

#### Viewing a random sample

In [29]:
%%time
if simulation.fourier_mode is not None:
    simulation.fourier_dataframe.sample(frac=0.1, replace=False)

CPU times: user 17.2 ms, sys: 0 ns, total: 17.2 ms
Wall time: 17 ms


#### Checking train/val/test splits again

In [30]:
%%time
n_total = len(simulation.dataframe)
n_train = len(simulation.dataframe[simulation.dataframe.type_of == "train"])
n_val = len(simulation.dataframe[simulation.dataframe.type_of == "val"])
n_test = len(simulation.dataframe[simulation.dataframe.type_of == "test"])
n_train_hamiltonians = len(simulation.train_ids)
n_val_hamiltonians = len(simulation.val_ids)
n_test_hamiltonians = len(simulation.test_ids)
n_total_hamiltonians = n_train_hamiltonians + n_val_hamiltonians + n_test_hamiltonians

print("% train: ", n_train/n_total)
print("% val: ",  n_val/n_total)
print("% test: ", n_test/n_total)
print("% train + val + test: ", (n_train+n_val+n_test)/n_total)
print("\n")
print("number of train hamiltonians: ", n_train_hamiltonians)
print("number of val hamiltonians: ", n_val_hamiltonians)
print("number of test hamiltonians: ", n_test_hamiltonians)
print("total number of hamiltonians: ", n_total_hamiltonians)
print("\n")
print("train ids: ", simulation.train_ids)
print("val ids: ", simulation.val_ids)
print("test ids: ", simulation.test_ids)

% train:  0.08474317939338516
% val:  0.7620789513793629
% test:  0.15317786922725193
% train + val + test:  1.0


number of train hamiltonians:  556
number of val hamiltonians:  5000
number of test hamiltonians:  1005
total number of hamiltonians:  6561


train ids:  [4402, 1513, 3136, 1910, 5224, 3876, 2678, 1339, 2660, 5114, 1381, 3482, 3448, 3387, 4600, 1122, 1817, 1676, 3743, 152, 3589, 3598, 3857, 1673, 4550, 6543, 4984, 3239, 3415, 5754, 3365, 3015, 3106, 5211, 3594, 2414, 1652, 6017, 2468, 4218, 5011, 56, 4355, 4696, 4908, 4404, 1465, 101, 3011, 3611, 1830, 2517, 5934, 1445, 1629, 2381, 5621, 2487, 2382, 1352, 2348, 1995, 4131, 5204, 2201, 3754, 5066, 1074, 1732, 2655, 5456, 355, 3001, 5438, 2785, 6365, 4422, 4988, 3013, 1285, 3434, 30, 4003, 6031, 5271, 5525, 1540, 2885, 3306, 1443, 2636, 4492, 937, 4224, 5038, 2337, 2986, 1376, 3016, 556, 5558, 3457, 2576, 6004, 5873, 6034, 4454, 3621, 3476, 3996, 1632, 4108, 2735, 2526, 109, 2180, 5212, 2508, 2505, 4646, 4859, 362, 1851, 256

#### Checking summaries

In [31]:
%%time
ham_summary = simulation.hamiltonian_summary
print("length of ham_summary: ", len(ham_summary))
ham_summary

length of ham_summary:  6561
CPU times: user 52 µs, sys: 1 µs, total: 53 µs
Wall time: 54.6 µs


t1    t2 type_of     0     1  phase  pred_phase
id                                                    
0    -2.0 -2.00    test  0.73  0.27    999           0
1    -2.0 -1.95    test  0.73  0.27      0           0
2    -2.0 -1.90    test  0.70  0.30      0           0
3    -2.0 -1.85    test  0.78  0.22      0           0
4    -2.0 -1.80    test  0.74  0.26      0           0
...   ...   ...     ...   ...   ...    ...         ...
6556  2.0  1.80    test  0.72  0.28      0           0
6557  2.0  1.85    test  0.76  0.24      0           0
6558  2.0  1.90    test  0.75  0.25      0           0
6559  2.0  1.95    test  0.73  0.27      0           0
6560  2.0  2.00    test  0.69  0.31    999           0

[6561 rows x 7 columns]

In [32]:
ham_summary.describe()

t1            t2            0            1        phase  \
count  6561.000000  6.561000e+03  6561.000000  6561.000000  6561.000000   
mean      0.000000 -4.331917e-18     0.707564     0.292436    25.002134   
std       1.169134  1.169134e+00     0.195065     0.195065   154.495657   
min      -2.000000 -2.000000e+00     0.370000     0.000000     0.000000   
25%      -1.000000 -1.000000e+00     0.520000     0.100000     0.000000   
50%       0.000000  0.000000e+00     0.700000     0.300000     1.000000   
75%       1.000000  1.000000e+00     0.900000     0.480000     1.000000   
max       2.000000  2.000000e+00     1.000000     0.630000   999.000000   

        pred_phase  
count  6561.000000  
mean      0.164457  
std       0.370718  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000

In [33]:
eigen_summary = simulation.eigenvector_summary
print("length of ham_summary: ", len(eigen_summary))
eigen_summary

length of ham_summary:  656100


id  phase  pred_phase type_of
0          0    999           0    test
1          0    999           0    test
2          0    999           0    test
3          0    999           0    test
4          0    999           0    test
...      ...    ...         ...     ...
656095  6560    999           1    test
656096  6560    999           0    test
656097  6560    999           0    test
656098  6560    999           1    test
656099  6560    999           1    test

[656100 rows x 4 columns]

#### Checking accuracies

In [34]:
simulation.accuracy

{'eigenvector_train': 0.8157374100719424,
 'eigenvector_val': 0.695974,
 'eigenvector_test': 0.5307938388625593,
 'hamiltonian_train': 0.9928057553956835,
 'hamiltonian_val': 0.6698,
 'hamiltonian_test': 0.44786729857819907}

#### Checking data stored in  memory

In [35]:
ham_summary_list = simulation.hamiltonian_summary_list
ham_summary_list

[]

In [36]:
eigen_summary_list = simulation.eigenvector_summary_list
eigen_summary_list

[]

In [37]:
accuracy_list = simulation.accuracy_list
accuracy_list

{'eigenvector_train': [],
 'eigenvector_val': [],
 'eigenvector_test': [],
 'hamiltonian_train': [],
 'hamiltonian_val': [],
 'hamiltonian_test': []}

In [38]:
#simulation.fourier_matrix

In [39]:
#simulation.fourier_matrix.shape

In [40]:
#simulation.fourier_matrix[:,0]

In [41]:
#simulation.fourier_matrix[:,1]

In [42]:
#np.exp(-1j*2*np.pi*3/100)

In [43]:
#for i in range(1,50):
#    print("\n")
#    print(i)
#    print(np.sum((np.real(simulation.fourier_matrix[:,i]) - np.real(simulation.fourier_matrix[:,-i]))**2))
#    print(np.sum((np.imag(simulation.fourier_matrix[:,i])+ np.imag(simulation.fourier_matrix[:,-i]))**2))

In [44]:
#print(simulation.fourier_matrix[:,0])

In [45]:
#print(simulation.fourier_matrix[:,50])